[package]
name = "pjltodo"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
pjltui = { version = "0.1.0", path = "../pjltui" }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["tracing"] }
