[package]
name = "sap2md"
version = "0.1.0"
edition = "2024"

[dependencies]
pjl-pandoc = { path = "../pjl-pandoc" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
