https://services.odata.org/V2/Northwind/Northwind.svc/$metadata

###
https://services.odata.org/V2/Northwind/Northwind.svc/Customers/$count

###
https://services.odata.org/V2/Northwind/Northwind.svc/Customers
Accept: application/json
